package dev.shadowsoffire.apothic_enchanting.api;

import java.util.List;

import dev.shadowsoffire.apothic_enchanting.table.ApothEnchantmentHelper;
import dev.shadowsoffire.apothic_enchanting.table.EnchantmentTableStats;
import net.minecraft.util.RandomSource;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.enchantment.EnchantmentInstance;

public interface EnchantableItem {

    /**
     * Allow the Item to perform manipulations to the selected list of enchantments.<br>
     * Note that this method must be deterministic respective to the random seed, and should always produce the same results for the same seed.<br>
     *
     * @param builtList The Enchantment List, as generated by {@link ApothEnchantmentHelper#buildEnchantmentList}
     * @param rand      The pre-seeded random
     * @param stack     The stack being enchanted (which is not currently enchanted)
     * @param level     The table level
     * @param quanta    The quanta value
     * @param arcana    The arcana value
     * @param treasure  If treasure enchantments can be selected or not.
     * @return The list of enchantments selected, given the context.
     */
    default List<EnchantmentInstance> selectEnchantments(List<EnchantmentInstance> builtList, RandomSource rand, ItemStack stack, int level, EnchantmentTableStats stats) {
        return builtList;
    }

}
